
import "./globals.css";
import { BackgroundBeamsWithCollision } from "@/components/ui/background-beams-with-collision";
import { Plus_Jakarta_Sans } from "next/font/google";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/sonner";

const fontSans = Plus_Jakarta_Sans({
  subsets:["latin"],
  weight:['300','400','500','600','700'],
  variable:'--font-sans'
});

export const metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen font-sans bg-dark-300 antialiased',fontSans.variable)}>
        <BackgroundBeamsWithCollision>
          <div className="w-screen min-h-screen flex flex-col justify-items-start ">
            <Navbar/>

            <div className="w-full h-[0.1px]  bg-gray-300"/>
            {children}
          </div>
        </BackgroundBeamsWithCollision>

        <Toaster position="top-right" richColors/>
      </body>

      
    </html>
  );
}
